apiVersion: apps/v1
kind: Deployment
metadata:
  name: phototheque-nginx
  labels:
    app: phototheque-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phototheque-nginx
  template:
    metadata:
      labels:
        app: phototheque-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: phototheque-nginx-config

# Commande qui va créer un ConfigMap phototheque-nginx-config que le Deployment va utiliser.
# kubectl create configmap phototheque-nginx-config --from-file=nginx.conf=nginx/dev/nginx.conf
# Les applys
# kubectl apply -f nginx/deployment.yaml
# kubectl apply -f nginx/service.yaml

# Vérifier que la config a été correctement crée
# kubectl get configmaps
# kubectl describe configmap phototheque-nginx-config

# On teste avec http://localhost:30080