apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
      - name: mongos
        image: mongo:6.0
        command:
          - mongos
          - "--configdb"
          - "configReplSet/configsvr-0.configsvr.default.svc.cluster.local:26050"
          - "--bind_ip_all"
        ports:
        - containerPort: 27017

# On applique tous les fichiers du repertoire sharding
# kubectl apply -f .

# Commandes à exécuter pour repartir de zero
# kubectl delete all --all
# kubectl delete pvc --all
# kubectl delete pv --all
# kubectl delete configmap --all
# kubectl delete secret --all
# kubectl delete ns <nom_du_namespace>