apiVersion: v1
kind: Service
metadata:
  name: phototheque-web-service
spec:
  selector:
    app: phototheque-web
  ports:
    - port: 3003
      targetPort: 3003
  type: NodePort # En lieu et place de NodePort car ClusterIP le rend accessible uniquement à l’intérieur du cluster, pas depuis ton navigateur ou ton poste local.